server:
  port: 8001
  
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/javiercbgr/xkcdgag
          searchPaths: config-data
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka